apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: bXl1c2VybmFtZQo= #Base64 encoded value of "mysuername"
  password: bXlwYXNzd29yZAo= #Base64 encoded value of "mypassword"